# Forces Jekyll to include the submodule folder
include: [wiki]

# Prevents Jekyll from ignoring files it thinks are "hidden" in submodules
exclude: []

# This tells Jekyll exactly how to handle folder URLs
defaults:
  - scope:
      path: "wiki"
    values:
      permalink: /wiki/:basename
