# Forces Jekyll to include the submodule folder
include: [wiki]

# Prevents Jekyll from ignoring files it thinks are "hidden" in submodules
exclude: []

# This tells Jekyll exactly how to handle folder URLs
defaults:
  - scope:
      path: "wiki"
    values:
      layout: "default"
      permalink: /wiki/:basename
      
brand:
  bg_color: "#E0E4E2"
  text_color: "#555555"
  link_color: "#6A8F6B"
  heading_color: "#162D26"
